export const courses = [
  {
    name: "Advanced React.js",
    date: "2025-09-30",
    subject: "React.js",
    location: "Stuttgart",
    participants: 20,
    notes: "Focus on hooks and context API",
    price: 2000,
    trainer_price: 500,
  },
  {
    name: "Advanced Next",
    date: "2025-10-01",
    subject: "NextJs",
    location: "Berlin",
    participants: 20,
    notes: "Focus on server-side rendering",
    price: 2000,
    trainer_price: 500,
  },
  {
    name: "Advanced Mongo",
    date: "2025-09-30",
    subject: "Mongodb",
    location: "Munich",
    participants: 20,
    notes: "Focus on aggregation and indexing",
    price: 2000,
    trainer_price: 500,
  },
  {
    name: "Node.js Masterclass",
    date: "2025-10-05",
    subject: "Node.js",
    location: "Hamburg",
    participants: 15,
    notes: "Deep dive into event loop and streams",
    price: 1800,
    trainer_price: 450,
  },
  {
    name: "GraphQL Fundamentals",
    date: "2025-10-10",
    subject: "GraphQL",
    location: "Cologne",
    participants: 25,
    notes: "Introduction to GraphQL schemas and queries",
    price: 1500,
    trainer_price: 400,
  },
  {
    name: "Docker for Developers",
    date: "2025-10-15",
    subject: "Docker",
    location: "Frankfurt",
    participants: 18,
    notes: "Learn containerization and orchestration",
    price: 2200,
    trainer_price: 550,
  },
  {
    name: "AWS Essentials",
    date: "2025-10-20",
    subject: "AWS",
    location: "Düsseldorf",
    participants: 22,
    notes: "Introduction to AWS services and cloud computing",
    price: 2500,
    trainer_price: 600,
  },
  {
    name: "Python for Data Science",
    date: "2025-10-25",
    subject: "Python",
    location: "Leipzig",
    participants: 20,
    notes: "Data analysis with Pandas and NumPy",
    price: 1700,
    trainer_price: 420,
  },
  {
    name: "Kubernetes Advanced",
    date: "2025-11-01",
    subject: "Kubernetes",
    location: "Dresden",
    participants: 15,
    notes: "Advanced topics in Kubernetes orchestration",
    price: 2300,
    trainer_price: 580,
  },
  {
    name: "JavaScript Fundamentals",
    date: "2025-11-05",
    subject: "JavaScript",
    location: "Stuttgart",
    participants: 25,
    notes: "Basics of JavaScript and ES6 features",
    price: 1200,
    trainer_price: 300,
  },
];
